#!/bin/bash

if [ -z "$1" ]; then
    node_port=8091;
    node_postfix="xx";
else
    node_port=`expr 9000 + $1`;
    node_postfix=$1
fi

erl_cookie=$(wget -O- -q --user Administrator --password asdasd --post-data="erlang:get_cookie()." http://127.0.0.1:$node_port/diag/eval; echo)
erl_cookie=${erl_cookie//\'}

erl_node=$(wget -O- -q --user Administrator --password asdasd --post-data="erlang:node()." http://127.0.0.1:$node_port/diag/eval; echo)
erl_node=${erl_node//\'}

this_node="node_$node_postfix@127.0.0.1"

echo "Local node: $this_node"
echo "Remote node: $erl_node"
echo "Cookie: $erl_cookie"

if [ -z "$erl_node" ]; then
    echo "Node No. $node_postfix is not started"
    exit 1
fi

echo erl -name $this_node -remsh $erl_node -setcookie $erl_cookie -kernel inetrc '"/Users/artem/work/cbmisc/hosts.cfg"'
erl -name $this_node -remsh $erl_node -setcookie $erl_cookie -kernel inetrc '"/Users/artem/work/cbmisc/hosts.cfg"'
